### ISSUE TITLE
Executable package doesn't pass command line parametrs

### ISSUE THREAD

**Issue by KindWizzard** [Nubisa/jxdocs#167]
Hi there.

Looks like there are some problems with command line applications. JXCore wrap doesn't pass parameters in to my application. I've created App.exe, then just tried to run it with arguments:
App.exe file.txt

**Comment by ktrzeciaknubisa** [comment]
Probably you are looking at `process.argv` starting from index \[2\], however for native packages there is no index \[0\] (*jx.exe*) since they are standalone. Therefore all `process.argv` are shifted left by one. Just call:
```js
console.log(process.argv);
```

and you should see that your argument is at index \[1\]:
```
[ 'C:\\jxcore\\temp\\argv\\App.exe', 'file.txt' ]
```

**Comment by KindWizzard** [comment]
Thank u!
